# config.yaml
issuer: http://localhost:5556/dex
storage:
  type: memory
web:
  http: 0.0.0.0:5556
staticClients:
  - id: example-app
    redirectURIs:
      - 'http://localhost:5555/callback'
      - 'http://localhost:5555/google/callback'
      - 'http://localhost:5555/microsoft/callback'
      - 'http://localhost:5555/github/callback'
      - 'http://localhost:5555/slack/callback'
      - 'http://localhost:5555/facebook/callback'
      - 'http://localhost:5555/apple/callback'
      - 'http://localhost:5555/okta/callback'
      - 'http://localhost:5555/cognito/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    public: true
staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "1234"
enablePasswordDB: true
connectors:
- type: mockCallback
  id: mock
  name: Example

# GitHub connector
- type: github
  id: github
  name: GitHub
  config:
    clientID: ${GITHUB_CLIENT_ID:github-client-id}
    clientSecret: ${GITHUB_CLIENT_SECRET:github-client-secret}
    redirectURI: http://localhost:5556/dex/callback/github
    loadAllGroups: true
    teamNameField: slug
    useLoginAsID: false

# Google connector
- type: google
  id: google
  name: Google
  config:
    clientID: ${GOOGLE_CLIENT_ID:google-client-id}
    clientSecret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
    redirectURI: http://localhost:5556/dex/callback/google
    hostedDomains: []

# Microsoft connector
- type: microsoft
  id: microsoft
  name: Microsoft
  config:
    clientID: ${MICROSOFT_CLIENT_ID:microsoft-client-id}
    clientSecret: ${MICROSOFT_CLIENT_SECRET:microsoft-client-secret}
    redirectURI: http://localhost:5556/dex/callback/microsoft
    tenant: common

# OIDC connector for Slack
- type: oidc
  id: slack
  name: Slack
  config:
    issuer: https://slack.com
    clientID: ${SLACK_CLIENT_ID:slack-client-id}
    clientSecret: ${SLACK_CLIENT_SECRET:slack-client-secret}
    redirectURI: http://localhost:5556/dex/callback/slack
    scopes: ["openid", "profile", "email"]

# OIDC connector for Facebook
- type: oidc
  id: facebook
  name: Facebook
  config:
    issuer: https://www.facebook.com
    clientID: ${FACEBOOK_CLIENT_ID:facebook-client-id}
    clientSecret: ${FACEBOOK_CLIENT_SECRET:facebook-client-secret}
    redirectURI: http://localhost:5556/dex/callback/facebook
    scopes: ["openid", "profile", "email"]

# OIDC connector for Okta - using mockCallback instead of oidc to avoid startup errors
- type: mockCallback
  id: okta
  name: Okta

# OIDC connector for AWS Cognito - using mockCallback instead of oidc to avoid startup errors
- type: mockCallback
  id: cognito
  name: AWS Cognito

# Note: Sign in with Apple requires private key and additional setup
# For testing purposes, we'll use a mock connector
- type: mockCallback
  id: apple
  name: Apple
