name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  LOG_LEVEL: info
  SWIFT_DETERMINISTIC_HASHING: 1
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image:
          - "swift:6.1"
        dex-image:
          - "ghcr.io/dexidp/dex:latest"
        include:
          - dex-image: ghcr.io/dexidp/dex:latest
    container:
      image: ${{ matrix.image }}
    services:
      dex:
        image: ${{ matrix.dex-image }}
        ports:
          - 5556:5556
        volumes:
          - ${{ github.workspace }}/infra/config.yaml:/etc/dex/config.yaml:ro
        env:
          DEX_ISSUER_URL: http://dex:5556/dex
        options: >-
          --health-cmd "curl -f http://localhost:5556/dex/.well-known/openid-configuration || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Wait for Dex to be ready
        run: |
          echo "Waiting for Dex to be ready..."
          max_attempts=30
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if curl -f http://dex:5556/dex/.well-known/openid-configuration > /dev/null 2>&1; then
              echo "Dex is ready!"
              break
            fi
            echo "Attempt $((attempt + 1))/$max_attempts: Dex not ready yet, waiting..."
            sleep 2
            attempt=$((attempt + 1))
          done
          
          if [ $attempt -eq $max_attempts ]; then
            echo "Dex failed to become ready after $max_attempts attempts"
            exit 1
          fi
          
          # Additional verification - check JWKS endpoint
          echo "Verifying JWKS endpoint..."
          if curl -f http://dex:5556/dex/keys > /dev/null 2>&1; then
            echo "JWKS endpoint is accessible!"
          else
            echo "Warning: JWKS endpoint not accessible, but continuing..."
          fi
      - name: Build
        run: swift build --build-tests --configuration debug -Xswiftc -enable-testing -Xswiftc -warnings-as-errors -Xcc -Werror --sanitize address --disable-xctest
      - name: Run Tests
        run: |
          swift test --skip-build --configuration debug --disable-xctest
        env:
          DEX_URL: http://dex:5556
          DEX_ISSUER_URL: http://dex:5556/dex
